spring:
  application:
    name: admin-server
  boot:
    admin:
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
server:
  port: 5000
eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:1111/eureka/
management:
  security:
    enabled: false