spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vw?characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: true
      test-on-return: true
      filters: slf4j,stat,wall
      filter:
        slf4j:
          enabled: true
      aop-patterns: com.yibo.springboothello.dao.*
  cloud:
    loadbalancer:
      retry:
        enabled: true
  sleuth:
    sampler:
      percentage: 1
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    sender:
      type: web
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.example.boottest.entity
logging:
  level:
    root: info
    com.yibo.springboothello.dao: debug
    org.springframework.web.servlet.DispatcherServlet: debug
eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:1111/eureka/
management:
  security:
    enabled: false