server:
  port: 9411
spring:
  application:
    name: zipkin-server
zipkin:
  storage:
    type: elasticsearch
    elasticsearch:
      cluster: elasticsearch_yibo
      hosts: http://localhost:9200
      index: zipkin
      index-shards: 5
      index-replicas: 1