server:
  port: 9411
spring:
  application:
    name: zipkin-server
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    continue-on-error: true
    initialize: true
    url: jdbc:mysql://localhost:3306/zipkin?characterEncoding=UTF-8&useSSL=false
  sleuth:
    enabled: false
zipkin:
  storage:
    type: mysql