server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:1111/eureka/
logging:
  level:
    com.yibo.ribbonconsumer.feign.MissionFeignClient: debug
    org.springframework.web.servlet.DispatcherServlet: debug
feign:
  hystrix:
    enabled: true