spring:
  application:
    name: ribbon-consumer
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:1111/eureka/
logging:
  level:
    com.yibo.ribbonconsumer.feign.MissionFeignClient: DEBUG
feign:
  hystrix:
    enabled: true