server:
  port: 8040
spring:
  sleuth:
    sampler:
      percentage: 1
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:1111/eureka/
management:
  security:
    enabled: false
zuul:
  routes:
    ribbon-consumer: /hello/**
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  PreRequestLogFilter:
    pre:
      disable: false
sidecar:
  health-uri: http://localhost:8060/health.json
  port: 8060