server:
  port: 8040
spring:
  application:
    name: gateway-zuul
eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:1111/eureka/
management:
  security:
    enabled: false
logging:
  level:
    com.netflix: debug
zuul:
  routes:
    ribbon-consumer: /hello/**